### ISSUE TITLE
Bug nas opções

### ISSUE THREAD

**Issue by smsn99** [Anpix/Civ5-PTBR#121]
Quando instalada a tradução, ao selecionar 'opções' no menu inicial, não aparece nada, além de não responder aos comandos para retroceder

**Comment by Anpix** [comment]
Vou dar uma olhada nessa questão. Obrigado por reportar o bug

**Comment by Anpix** [comment]
@smsn99 fiz o teste aqui, e está tudo ok.
Por favor, quando colocar os arquivos na pasta do jogo, lembre-se de substituir os arquivos.
Me informe caso não consiga resolver, que te ajudo.
