### ISSUE TITLE
Andamento do Projeto

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [Anpix/Civ5-PTBR#16]
Gostaria de saber como esta o andamento do projeto @Anpix @passarinhu @gdcs321

**Comment by Anpix** [comment]
Nossa! Quase um ano depois, mas... Estamos avançando. De vez enquanto alguém faz uma contribuição

**Comment by afmenez** [comment]
O projeto ainda está vivo?  Mandei algumas contribuições ontem e hoje, mas agora vi que existem contribuições com mais de 6 meses que ainda não foram aceitas...

**Comment by HenriqueCRodrigues** [comment]
@afmenez Tenho interesse em finalizar, se vc tiver interesse, faço fork e podemos continuar de onde esse projeto parou!

**Comment by Anpix** [comment]
Falae @afmenez e @HenriqueCRodrigues ... Ainda tô por aqui, só não tem tido muita contribuição ultimamente, daí fiquei um pouco inativo.

**Comment by afmenez** [comment]
Que bom que o projeto ainda está vivo.  Vou fazer mais algumas contribuições então. :)

**Comment by afmenez** [comment]
@Anpix, fiz várias outras contribuições, algumas há mais de um mês, e estão paradas.  Entendo que algumas são bem grandes e precisam de tempo para revisão, mas outras são pequenas (#31, #32, #37, #41, #42, #43 e #44) e poderiam ser integradas sem investir tanto tempo...

**Comment by Anpix** [comment]
Beleza... Estou dando uma olhada, e já fiz o merge de algumas, mas outras ainda tem algumas observações
