### ISSUE TITLE
Cavalheirismo ficaria melhor como Bravura.

### ISSUE THREAD

**Issue by fsbenvenutti** [Anpix/Civ5-PTBR#17]

**Comment by afmenez** [comment]
Acredito que a tradução correta no contexto do jogo seja Cavalaria.

**Comment by afmenez** [comment]
Lendo a descrição da tecnologia, acredito que a melhor tradução seria "Código da Cavalaria".

**Comment by fsbenvenutti** [comment]
Verdade, parece o mais adequado mesmo.

Em qui, 16 de mai de 2019 16:38, Alexandre Folle de Menezes <
notifications@github.com> escreveu:
