### ISSUE TITLE
Testar o funcionamento do caractere º dentro do Jogo

### ISSUE THREAD

**Issue by Anpix** [Anpix/Civ5-PTBR#30]
Não testei o funcionamento do caractere º dentro do Jogo

_Originally posted by @Anpix in https://github.com/Anpix/Civ5-PTBR/pull/28#issuecomment-494500385_

**Comment by afmenez** [comment]
Testados "º" e "ª", funcionam sem problemas.

**Comment by Anpix** [comment]
Você é fera @afmenez !
