### ISSUE TITLE
Confusão nas traduções de Spearman, Lancer e Pikeman

### ISSUE THREAD

**Issue by afmenez** [Anpix/Civ5-PTBR#34]
Existe muita confusão na tradução dos três termos,  sendo que um foi trocado pelo outro em dezenas de lugares.
Spearman e Lancer foram traduzidos para o mesmo termo (Lanceiro), o que causa muita confusão no texto.  Por algum motivo, em alguns lugares Pikeman também foi traduzido para Lanceiro.

**Comment by afmenez** [comment]
Estou corrigindo tudo, mas estou com dificuldade para achar uma tradução para Spearman.  Coloquei assim:
- Spearman: Lançador
- Pikeman: Piqueiro
- Lancer: Lanceiro
Alguém tem alguma sugestão melhor?

**Comment by afmenez** [comment]
No Civilization VI, o Spearman é Lanceiro, mas não há o Lancer.

**Comment by gdcs321** [comment]
Creio que "Lanceiro" fica melhor, pois "Guerreiro com Lança" é muito genérico. Se a tradução de Lanceiro no Civ VI é Spearman, coloque Lancer como Lançador. Particularmente acho que deveria deixar ambas traduções como lanceiro, já que, para mim, é uma forma diferente de dizer a mesma coisa.

**Comment by afmenez** [comment]
O "Lancer" é uma unidade montada, com lança longa que é segurada pelo cavaleiro para derrubar o inimigo: https://pt.wikipedia.org/wiki/Lanceiro
Já o "Spearman" é uma unidade a pé, que arremessa a lança no inimigo.
A confusão toda é porque duas coisas diferentes ("lance" e "spear") têm o mesmo nome em portugês.  Mas usar o mesmo nome para as duas unidades como está hoje não funciona em termos de interface do usuário.
Eu preferi usar Lanceiro apenas para "Lancer", que já é um termo consagrado em português.  E concordo em mudar a tradução de "Spearman" se aparecer uma sugestão melhor.

**Comment by gdcs321** [comment]
Que tal "Cavaleiro Lanceiro" para "Lancer" e "Lanceiro" para "Spearman"?

**Comment by afmenez** [comment]
Até faz sentido lógico, mas não com o termo consagrado.

**Comment by afmenez** [comment]
O Civ6 chama o Spearman de Lanceiro, e não há o Lancer.  O Civ5 Espanhol os chama de Lancero e Lancero Montado, acho que podemos seguir nesse sentido mesmo.
