### ISSUE TITLE
Tradução para so baseados em linux

### ISSUE THREAD

**Issue by gugatxr** [Anpix/Civ5-PTBR#9]
Oi, 

Eu utilizo Ubuntu, e aqui as pastas estão todas em letras minusculas.
Gostaria de saber se é possível fazermos uma branch para deixar uma versão assim.
Já corrigi os arquivos, gostaria de compartilhar.

Valeu

**Comment by Anpix** [comment]
Claro, @gugatxr 
Faça um pull request com esta alteração.

Obrigado.

**Comment by vhbsouza** [comment]
@gugatxr e @Anpix Acho que não precisa disso, é só baixar no formato zip e extrair assim por exemplo:

`unzip -LL foo.zip`

ele já extrai e converte tds os nomes de pastas e arquivos pra minúsculo

**Comment by gugatxr** [comment]
Show, fica mais fácil.

Em 29 de dez de 2016 14:22, "Victor Hugo Bernardes de Souza" <
notifications@github.com> escreveu:

@gugatxr <https://github.com/gugatxr> e @Anpix <https://github.com/Anpix>
Acho que não precisa disso, é só baixar no formato zip e extrair assim por
exemplo:

unzip -LL foo.zip

ele já extrai e converte tds os nomes de pastas e arquivos pra minúsculo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Anpix/Civ5-PTBR/issues/9#issuecomment-269654065>, or mute
the thread
