### ISSUE TITLE
Erro na tradução dos Barcos de Serviço

### ISSUE THREAD

**Issue by erycson** [Anpix/Civ5-PTBR#90]
Imagem do erro: https://prnt.sc/qkwm23

**Comment by Anpix** [comment]
Correção realizada
#92

**Comment by Anpix** [comment]
@erycson se possível, pode efetuar um teste pra ver se foi concluído com sucesso?
Não tenho o Civ5 instalado aqui no momento, e estou sem espaço livre pra download por enquanto.

**Comment by erycson** [comment]
> @erycson se possível, pode efetuar um teste pra ver se foi concluído com sucesso?
> Não tenho o Civ5 instalado aqui no momento, e estou sem espaço livre pra download por enquanto.

Opa, posso sim, assim que der, estarei respondendo

**Comment by erycson** [comment]
Cara, não até tentei testar, mas não sei como fazer para aquela janelinha abrir novamente

**Comment by afmenez** [comment]
Falha minha.  Está corrogido sim.
